--SELECT * FROM Stuff
-- SELECT nameOF FROM STUFF
-- WHERE typeOF = 'Vegetable'
-- SELECT nameOF FROM STUFF
-- WHERE typeOF = 'Fruit'
-- SELECT nameOF FROM Stuff
-- SELECT DISTINCT colour FROM Stuff
-- SELECT nameOF FROM Stuff 
-- WHERE typeOF = 'Fruit' AND colour = 'Red'
